name: paisa_khai
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  csv: ^6.0.0
  cupertino_icons: ^1.0.8
  file_picker: ^10.3.10
  fl_chart: ^1.1.1
  flutter:
    sdk: flutter
  freezed_annotation: ^3.1.0
  hive_ce_flutter: ^2.3.4
  intl: ^0.20.2
  json_annotation: ^4.10.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  uuid: ^4.5.2

dev_dependencies:
  build_runner: ^2.10.5
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.2.4
  hive_ce_generator: ^1.10.1
  json_serializable: ^6.12.0

flutter:
  uses-material-design: true
