name: paisa_khai
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  collection: ^1.19.1
  csv: ^6.0.0
  cupertino_icons: ^1.0.8
  equatable: ^2.0.8
  file_picker: ^10.3.10
  fl_chart: ^1.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_local_notifications: ^20.0.0
  flutter_web_plugins:
    sdk: flutter
  freezed_annotation: ^3.1.0
  go_router: ^17.1.0
  google_fonts: ^8.0.1
  hive_ce_flutter: ^2.3.4
  image_picker: ^1.2.1
  intl: ^0.20.2
  json_annotation: ^4.10.0
  path: ^1.9.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  rename_app: ^1.6.5
  timezone: ^0.10.1
  universal_platform: ^1.1.0
  uuid: ^4.5.2

dev_dependencies:
  build_runner: ^2.10.5
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.2.5
  hive_ce_generator: ^1.11.1
  json_serializable: ^6.12.0

flutter:
  uses-material-design: true
